version: '3.8'

services:
  db:
    image: postgres:16
    container_name: aurora_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aurora_users
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d aurora_users']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: